# Generated by Django 4.2.2 on 2023-06-24 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('user', '0002_privilege_user_privileges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='belongs_to_manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.manager'),
        ),
    ]
