# Generated by Django 4.2.2 on 2023-07-06 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_belongs_to_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAllocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('psection', models.CharField(blank=True, default='', max_length=255)),
                ('ssection', models.CharField(blank=True, default='', max_length=255)),
                ('pposition', models.IntegerField(default=0)),
                ('sposition', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='privilege',
            name='pageallocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='privileges', to='user.pageallocation'),
        ),
    ]
