# Generated by Django 4.2.2 on 2023-06-22 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salesperson', '0001_initial'),
        ('lead', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='imported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_imported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='qualified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_qualified', to='salesperson.salesperson'),
        ),
    ]
